apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
        - name: loyalty-service
          image: loyalty-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
spec:
  selector:
    app: loyalty-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
